services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - docmost-db
      - docmost-redis
    environment:
      APP_URL: 'http://localhost:3000'
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: postgresql://docmost:${DB_PASSWORD}@docmost-db:5432/docmost?schema=public
      REDIS_URL: 'redis://docmost-redis:6379'
      # Mail servers
      MAIL_DRIVER: ${MAIL_DRIVER}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      # S3
      STORAGE_DRIVER: s3
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - docmost:/app/data/storage
    networks:
      - docmost-networks

  docmost-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - docmost-networks

  docmost-redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    networks:
      - docmost-networks
    volumes:
      - redis_data:/data

volumes:
  docmost:
  db_data:
  redis_data:

networks:
  docmost-networks:
    name: docmost-networks
