services:
  portainer:
    container_name: arisa_portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
    networks:
      portainer-networks:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
networks:
  portainer-networks:
    name: portainer-networks
    ipam:
      driver: default
volumes:
  portainer_data: