version: '3.7'
services:
  pgadmin4:
      image: elestio/pgadmin:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: anataarisa@gmail.com
        PGADMIN_DEFAULT_PASSWORD: Vinh12345.
        PGADMIN_LISTEN_PORT: 5050
      ports:
      - "5050:5050"
