version: '3.8'
services:
  semaphore-postgres:
    image: postgres:14.12-bullseye
    container_name: semaphore_postgres
    restart: unless-stopped
    hostname: semaphore-postgres
    environment:
      POSTGRES_PASSWORD: semaphore
      POSTGRES_USER: semaphore
      POSTGRES_DB: semaphore
    volumes:
      - semaphore-postgres:/var/lib/postgresql/data
    networks:
      semaphore-networks:

  semaphore:
    container_name: arisa_semaphore
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: semaphore-postgres # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 5432 # change to 5432 for postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_DB_DIALECT: postgres # for postgres, change to: postgres
      SEMAPHORE_ADMIN_PASSWORD: 
      SEMAPHORE_ADMIN_NAME: Arisa
      SEMAPHORE_ADMIN_EMAIL: arisa@email.com
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
    networks:
      semaphore-networks:
    
volumes:
  semaphore-postgres: # to use postgres, switch to: semaphore-postgres
  
networks:
  semaphore-networks:
    name: semaphore-networks
    ipam:
      driver: default